/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-south-1",
    "aws_appsync_graphqlEndpoint": "https://by3utz4pbbddzcwdxg5krhze2i.appsync-api.ap-south-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-south-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-iwmdzgqnfzcrbe2fnumiwgxk64",
    "aws_cognito_identity_pool_id": "ap-south-1:6eb52261-4df6-4948-86b5-277cb1606ee9",
    "aws_cognito_region": "ap-south-1",
    "aws_user_pools_id": "ap-south-1_9E182WyAi",
    "aws_user_pools_web_client_id": "3na0l2qtdnq4dkd44a3qoiobqo",
    "oauth": {},
    "aws_user_files_s3_bucket": "postagram80f427e966634e6ebbc6978be19bd2c980112-dev",
    "aws_user_files_s3_bucket_region": "ap-south-1",
    "region": "ap-south-1"
};


export default awsmobile;
